# run the testsuite on travis-ci.com
---
# versions to run on
env:
  - PG_SUPPORTED_VERSIONS=9.5
  - PG_SUPPORTED_VERSIONS=9.6
  - PG_SUPPORTED_VERSIONS=10
  - PG_SUPPORTED_VERSIONS=11
  - PG_SUPPORTED_VERSIONS=12 DIST=xenial-pgdg-testing

language: C
dist: xenial
sudo: required

before_install:
  # apt.postgresql.org is already configured, we just need to add devel
  - '[ "$DIST" ] && sudo sed -i -e "s/pgdg.*/pgdg-testing main $PG_SUPPORTED_VERSIONS/" /etc/apt/sources.list.d/pgdg*.list'
  - sudo apt-get -qq update

install:
  - export DEBIAN_FRONTEND=noninteractive # suppress warnings about deprecated PostgreSQL versions
  - sudo apt-get install bison debhelper fakeroot flex postgresql-server-dev-$PG_SUPPORTED_VERSIONS postgresql-server-dev-all/${DIST:=xenial-pgdg}
  # install PostgreSQL $PG_SUPPORTED_VERSIONS if not there yet
  - |
    if [ ! -x /usr/lib/postgresql/$PG_SUPPORTED_VERSIONS/bin/postgres ]; then
      sudo /etc/init.d/postgresql stop # stop postgresql before installing the server
      sudo apt-get install postgresql-$PG_SUPPORTED_VERSIONS
    fi
  # stop the travis-provided cluster
  - sudo /etc/init.d/postgresql stop
  - pg_lsclusters
  - dpkg -l postgresql\* | cat

script:
  - pg_buildext updatecontrol
  - dpkg-buildpackage -us -uc -rfakeroot -b
  - for deb in ../*.deb; do echo "$deb:"; dpkg-deb --info $deb; dpkg-deb --contents $deb; done
  - sudo dpkg -i ../*.deb
  - pg_buildext -i '--locale=C.UTF-8' installcheck
